version: "3"
services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
  go-backend:
    container_name: go-backend
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_CONN_STRING: "mongodb://mongodb:27017"
    depends_on:
      - mongodb
  todo-ui:
    container_name: todo-ui
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - go-backend
volumes:
  db-data:
  mongo-config:
